[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200